---
# tasks file for ntp
- name: install ntpdate
  apt:
    pkg: ntpdate
    state: present

- name: time synchronization
  ansible.builtin.shell:
    cmd: sudo ntpdate -u {{ ntpserver }}

- name: Setup CRON job for time synchronization
  ansible.builtin.cron:
    name: "Synchronize time"
    minute: "*"
    weekday: "*"
    hour: "24"
    job: "sudo ntpdate -u {{ ntpserver }}"
    user: root
    cron_file: time_update.cron
