---
# tasks file for nginx
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 86400
  changed_when: false

- name: Ensure nginx is installed.
  apt:
    name: nginx
    state: present

#- name: Disable default conf
#  become: true
#  ansible.builtin.shell: cd /etc/nginx/conf.d/ && mv default.conf default.conf.disable

- name: Copy nginx configuration in place.
  template:
    src: kibana.conf
    dest: /etc/nginx/conf.d/kibana.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

